name: Deployment

on:
    push:
        branches: [main]

jobs:
    examples-and-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install and Build
              run: |
                  npm install
                  npm run build

            - name: Install and Build examples
              working-directory: examples
              run: |
                  npm ci --legacy-peer-deps
                  npm run build
                  
            - name: Install and Build docusaurus docs
              working-directory: docs
              run: |
                  npm ci
                  npm run build

            # - name: Copy README.md to docs
            #   run: |
            #     sed -i 's+\./docs/+./+g' README.md
            #     cp README.md docs/README.md

            - name: Setup Out Folder
              run: |
                  mkdir -p out/docs
                  mkdir -p out/examples
                  cp -r docs/build out/docs
                  cp -r examples/dist/* out/examples

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  branch: gh-pages
                  folder: out
    publish-npm-package:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write 
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/

            - name: Install Dependencies
              run: npm install

            - name: Check
              run: npm run check

            - name: Build
              run: npm run build

            - name: Deploy
              run: npm publish --access public
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    publish-github-package:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write 
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://npm.pkg.github.com/

            - name: Install Dependencies
              run: npm install
              env:
                NODE_AUTH_TOKEN: ${{ secrets.PRIVATE_GITHUB_TOKEN }}

            - name: Check
              run: npm run check

            - name: Build
              run: npm run build

            - name: Deploy
              run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
